///////////////////////////////////////////////
// This file was generated by Link2M utility //
///////////////////////////////////////////////

#include "rectangle.h"
#include "c:\prog\O2M\Import\In.h"
#include "c:\prog\O2M\Import\Out.h"
#include "c:\prog\O2M\Import\FileIO.h"
#include "triangle.h"
#include "figure.h"
#include "figureProc.h"
#include "container.h"
#include "c:\prog\O2M\Import\Console.h"

//figure.fig<rect>
const int figure::fig::O2M_SID_rect = 1;

void figure::fig::O2M_INIT_rect(fig* O2M_PCASE)
{
	O2M_PCASE->O2M_SPEC_rect = new rectangle::rect;
	O2M_PCASE->O2M_FREE = O2M_FREE_rect;
	O2M_PCASE->O2M_SID = O2M_SID_rect;
}

void figure::fig::O2M_FREE_rect(fig* O2M_PCASE)
{
	delete O2M_PCASE->O2M_SPEC_rect;
}

//figure.fig<trian>
const int figure::fig::O2M_SID_trian = 2;

void figure::fig::O2M_INIT_trian(fig* O2M_PCASE)
{
	O2M_PCASE->O2M_SPEC_trian = new triangle::trian;
	O2M_PCASE->O2M_FREE = O2M_FREE_trian;
	O2M_PCASE->O2M_SID = O2M_SID_trian;
}

void figure::fig::O2M_FREE_trian(fig* O2M_PCASE)
{
	delete O2M_PCASE->O2M_SPEC_trian;
}

//COMMON PROCEDURE "Perimeter" declared in module "figure"
void* O2M_COMMON_figure_Perimeter(figure::fig* p0)
{
	if (p0->O2M_SID_rect == p0->O2M_SID) return (void*)figure::O2M_HANDLER_Perimeter_0;
	if (p0->O2M_SID_trian == p0->O2M_SID) return (void*)figure::O2M_HANDLER_Perimeter_1;
	return 0;
}

//COMMON PROCEDURE "Output" declared in module "figure"
void* O2M_COMMON_figure_Output(figure::fig* p0)
{
	if (p0->O2M_SID_rect == p0->O2M_SID) return (void*)figure::O2M_HANDLER_Output_2;
	if (p0->O2M_SID_trian == p0->O2M_SID) return (void*)figure::O2M_HANDLER_Output_3;
	return 0;
}

//COMMON PROCEDURE "FileOutput" declared in module "figure"
void* O2M_COMMON_figure_FileOutput(figure::fig* p0)
{
	if (p0->O2M_SID_rect == p0->O2M_SID) return (void*)figure::O2M_HANDLER_FileOutput_4;
	if (p0->O2M_SID_trian == p0->O2M_SID) return (void*)figure::O2M_HANDLER_FileOutput_5;
	return 0;
}

