/////////////////////////////////////////////
// This file was generated by O2M compiler //
/////////////////////////////////////////////

#include "figureTest.h"
#include "_O2M_ppp.cpp"

void O2M_SYS_main_init() {
	figureTest::O2M_SYS_figureTest();
}
