/////////////////////////////////////////////
// This file was generated by O2M compiler //
/////////////////////////////////////////////

#ifndef O2M_H_FILE__O2M_main
#define O2M_H_FILE__O2M_main

#include "figureTest.h"

void O2M_SYS_main_init();

#endif
