/////////////////////////////////////////////
// This file was generated by O2M compiler //
/////////////////////////////////////////////

#ifndef O2M_H_FILE__O2M_sys
#define O2M_H_FILE__O2M_sys

#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <math.h>
#include "_O2M_ppp.h"

long MOD(const long x, const long y);
int ORD(const char ch);
void COPY(const char *x, const int x_size, char *v, const int v_size);
int O2M_SET_RANGE(const int l, const int h);

#endif
