/////////////////////////////////////////////
// This file was generated by O2M compiler //
/////////////////////////////////////////////

#ifndef O2M_H_FILE_figureTest
#define O2M_H_FILE_figureTest
#include "_O2M_sys.h"
#include "c:\prog\O2M\Import\In.h"
#include "c:\prog\O2M\Import\Out.h"
#include "c:\prog\O2M\Import\FileIO.h"
#include "c:\prog\O2M\Import\Console.h"
#include "figure.h"
#include "rectangle.h"
#include "triangle.h"
#include "figureProc.h"
#include "container.h"
namespace figureTest {
//MODULE INITIALIZATION
void O2M_SYS_figureTest();
}
#endif
