/////////////////////////////////////////////
// This file was generated by O2M compiler //
/////////////////////////////////////////////

//MODULE figureTest;
#include "figureTest.h"
using namespace figureTest;

//IMPORT
//In
//Out
//FileIO
//Console
//figure
//rectangle
//triangle
//figureProc
//container

//VAR
namespace {int flag;}
namespace {container::cont c;}
namespace {figure::Pfig* pf;}
namespace {FileIO::TFile inFile;}
namespace {FileIO::TFile outFile;}
namespace {char str[100];}

/////////////////////////////////////////////
//MODULE INITIALIZATION
void figureTest::O2M_SYS_figureTest() {
	//imports initialisation
	static bool O2M_SYS_was_started(false);
	if (O2M_SYS_was_started) return;
	O2M_SYS_was_started = true;
	In::O2M_SYS_In();
	Out::O2M_SYS_Out();
	FileIO::O2M_SYS_FileIO();
	Console::O2M_SYS_Console();
	figure::O2M_SYS_figure();
	rectangle::O2M_SYS_rectangle();
	triangle::O2M_SYS_triangle();
	figureProc::O2M_SYS_figureProc();
	container::O2M_SYS_container();
//BEGIN
	Out::String((char*)"Input name of source file: ", 28);
	In::String((char*)str, 100);
	inFile.Assign((char*)str, 100);
	inFile.Reset();
	Out::String((char*)"Input name of output file: ", 28);
	In::String((char*)str, 100);
	outFile.Assign((char*)str, 100);
	outFile.Rewrite();
	container::Init(&c);
	Out::String((char*)"Initialed Container is:", 24);
	container::Output(&c);
	Out::Ln();
	flag = container::FileInput(&inFile, &c);
	Out::String((char*)"Result Container is:", 21);
	Out::Ln();
	container::Output(&c);
	flag = outFile.WriteString((char*)"Result Container is:", 21);
	flag = outFile.Ln();
	container::FileOutput(&outFile, &c);
	Out::String((char*)"Input figures from console. ", 29);
	Out::Ln();
	container::Input(&c);
	Out::String((char*)"Result Container after console input is:", 41);
	Out::Ln();
	container::Output(&c);
	flag = outFile.WriteString((char*)"Result Container after console input  is:", 42);
	flag = outFile.Ln();
	container::FileOutput(&outFile, &c);
	inFile.Close();
	outFile.Close();
}
//END figureTest.
