/////////////////////////////////////////////
// This file was generated by O2M compiler //
/////////////////////////////////////////////

//MODULE rectangle;
#include "rectangle.h"
using namespace rectangle;

//IMPORT
//In
//Out
//FileIO

//VAR

/////////////////////////////////////////////
//PROCEDURE New
Prect* rectangle::New(int x, int y) {
	Prect* O2M_RESULT;
//VAR
Prect* tmp;
//BEGIN
	tmp = new(Prect);
	tmp->x = x;
	tmp->y = y;
	O2M_RESULT = tmp;
	goto O2M_RETURN;
	O2M_RETURN:;
	return O2M_RESULT;
}
//END New;

/////////////////////////////////////////////
//PROCEDURE Init
void rectangle::Init(rect* r, int x, int y) {
//VAR
//BEGIN
	r->x = x;
	r->y = y;
}
//END Init;

/////////////////////////////////////////////
//PROCEDURE Perimeter
double rectangle::Perimeter(rect* r) {
	double O2M_RESULT;
//VAR
//BEGIN
	O2M_RESULT = ((r->x + r->y) * 2);
	goto O2M_RETURN;
	O2M_RETURN:;
	return O2M_RESULT;
}
//END Perimeter;

/////////////////////////////////////////////
//PROCEDURE Input
void rectangle::Input(rect* r) {
//VAR
//BEGIN
	Out::String((char*)"x = ", 5);
	In::Int(r->x);
	Out::String((char*)"y = ", 5);
	In::Int(r->y);
}
//END Input;

/////////////////////////////////////////////
//PROCEDURE Output
void rectangle::Output(rect* r) {
//VAR
//BEGIN
	Out::String((char*)"Rectangle: x = ", 16);
	Out::Int(r->x, 0);
	Out::String((char*)", y = ", 7);
	Out::Int(r->y, 0);
	Out::String((char*)",   perimemter = ", 18);
	Out::Real(Perimeter(r), 0);
	Out::Ln();
}
//END Output;

/////////////////////////////////////////////
//PROCEDURE FileInput
void rectangle::FileInput(FileIO::TFile* inFile, rect* r) {
//VAR
int f;
//BEGIN
	f = inFile->ReadInt(r->x);
	f = inFile->ReadInt(r->y);
}
//END FileInput;

/////////////////////////////////////////////
//PROCEDURE FileOutput
void rectangle::FileOutput(FileIO::TFile* outFile, rect* r) {
//VAR
int flag;
//BEGIN
	flag = outFile->WriteString((char*)"Rectangle: x = ", 16);
	flag = outFile->WriteInt(r->x, 7);
	flag = outFile->WriteString((char*)", y = ", 7);
	flag = outFile->WriteInt(r->y, 7);
	flag = outFile->WriteString((char*)",   perimemter = ", 18);
	flag = outFile->WriteReal(Perimeter(r), 7);
	flag = outFile->Ln();
}
//END FileOutput;

/////////////////////////////////////////////
//MODULE INITIALIZATION
void rectangle::O2M_SYS_rectangle() {
	//imports initialisation
	static bool O2M_SYS_was_started(false);
	if (O2M_SYS_was_started) return;
	O2M_SYS_was_started = true;
	In::O2M_SYS_In();
	Out::O2M_SYS_Out();
	FileIO::O2M_SYS_FileIO();
//BEGIN
}
//END rectangle.
