/////////////////////////////////////////////
// This file was generated by O2M compiler //
/////////////////////////////////////////////

#ifndef O2M_H_FILE_triangle
#define O2M_H_FILE_triangle
#include "_O2M_sys.h"
#include "c:\prog\O2M\Import\In.h"
#include "c:\prog\O2M\Import\Out.h"
#include "c:\prog\O2M\Import\FileIO.h"
namespace triangle {
struct trian;
typedef trian Ptrian;
struct trian;
struct trian {
	virtual const char* O2M_SYS_ID() {return "trian@triangle";};
	int a;
	int b;
	int c;
};
//PROCEDURE New
Ptrian* New(int a, int b, int c);
//PROCEDURE Init
void Init(trian* t, int a, int b, int c);
//PROCEDURE Perimeter
double Perimeter(trian* t);
//PROCEDURE Input
void Input(trian* t);
//PROCEDURE Output
void Output(trian* t);
//PROCEDURE FileInput
void FileInput(FileIO::TFile* inFile, trian* t);
//PROCEDURE FileOutput
void FileOutput(FileIO::TFile* outFile, trian* t);
//MODULE INITIALIZATION
void O2M_SYS_triangle();
}
#endif
