/////////////////////////////////////////////
// This file was generated by O2M compiler //
/////////////////////////////////////////////

#ifndef O2M_H_FILE_addFigureCirc
#define O2M_H_FILE_addFigureCirc
#include "_O2M_sys.h"
#include "c:\prog\O2M\Import\In.h"
#include "c:\prog\O2M\Import\Out.h"
#include "c:\prog\O2M\Import\FileIO.h"
#include "figure.h"
#include "circle.h"
namespace addFigureCirc {
//HANDLER PROCEDURE Perimeter
double O2M_HANDLER_Perimeter_0(figure::fig* c);
//HANDLER PROCEDURE Output
void O2M_HANDLER_Output_1(figure::fig* c);
//HANDLER PROCEDURE FileOutput
void O2M_HANDLER_FileOutput_2(FileIO::TFile* outFile, figure::fig* c);
//MODULE INITIALIZATION
void O2M_SYS_addFigureCirc();
}
#endif
