/////////////////////////////////////////////
// This file was generated by O2M compiler //
/////////////////////////////////////////////

#ifndef O2M_H_FILE_figure
#define O2M_H_FILE_figure
#include "_O2M_sys.h"
#include "c:\prog\O2M\Import\In.h"
#include "c:\prog\O2M\Import\Out.h"
#include "c:\prog\O2M\Import\FileIO.h"
#include "rectangle.h"
#include "triangle.h"
namespace figure {
struct fig;
typedef fig Pfig;
//COMMON PROCEDURE Perimeter
double Perimeter(fig* f);
//HANDLER PROCEDURE Perimeter
double O2M_HANDLER_Perimeter_0(fig* r);
//HANDLER PROCEDURE Perimeter
double O2M_HANDLER_Perimeter_1(fig* t);
//COMMON PROCEDURE Output
void Output(fig* f);
//HANDLER PROCEDURE Output
void O2M_HANDLER_Output_2(fig* r);
//HANDLER PROCEDURE Output
void O2M_HANDLER_Output_3(fig* t);
//COMMON PROCEDURE FileOutput
void FileOutput(FileIO::TFile* outFile, fig* f);
//HANDLER PROCEDURE FileOutput
void O2M_HANDLER_FileOutput_4(FileIO::TFile* outFile, fig* r);
//HANDLER PROCEDURE FileOutput
void O2M_HANDLER_FileOutput_5(FileIO::TFile* outFile, fig* t);
//MODULE INITIALIZATION
void O2M_SYS_figure();
}
#endif
