/////////////////////////////////////////////
// This file was generated by O2M compiler //
/////////////////////////////////////////////

//MODULE container;
#include "container.h"
using namespace container;

//IMPORT
//In
//Out
//FileIO
//figure
//figureProc

//VAR
namespace {short maxSize = 100;}

/////////////////////////////////////////////
//PROCEDURE New
Pcont* container::New() {
	Pcont* O2M_RESULT;
//VAR
Pcont* tmp;
//BEGIN
	tmp = new(Pcont);
	tmp->size = 0;
	O2M_RESULT = tmp;
	goto O2M_RETURN;
	O2M_RETURN:;
	return O2M_RESULT;
}
//END New;

/////////////////////////////////////////////
//PROCEDURE Init
void container::Init(cont* c) {
//VAR
//BEGIN
	c->size = 0;
}
//END Init;

/////////////////////////////////////////////
//PROCEDURE AddFigure
void container::AddFigure(cont* c, figure::Pfig* f) {
//VAR
//BEGIN
	c->fig[c->size] = f;
	c->size = c->size + 1;
}
//END AddFigure;

/////////////////////////////////////////////
//PROCEDURE Input
void container::Input(cont* c) {
//VAR
int flag;
int tag;
figure::Pfig* pf;
int i;
//BEGIN
	i = 0;
	pf = figureProc::Input();
	while(pf != 0) {
		i = i + 1;
		AddFigure(c, pf);
		pf = figureProc::Input();
	};
	goto O2M_RETURN;
	O2M_RETURN:;
}
//END Input;

/////////////////////////////////////////////
//PROCEDURE FileInput
int container::FileInput(FileIO::TFile* inFile, cont* c) {
	int O2M_RESULT;
//VAR
int flag;
int tag;
figure::Pfig* pf;
int i;
//BEGIN
	i = 0;
	pf = figureProc::FileInput(inFile);
	while(pf != 0) {
		i = i + 1;
		AddFigure(c, pf);
		pf = figureProc::FileInput(inFile);
	};
	O2M_RESULT = i;
	goto O2M_RETURN;
	O2M_RETURN:;
	return O2M_RESULT;
}
//END FileInput;

/////////////////////////////////////////////
//PROCEDURE Output
void container::Output(cont* c) {
//VAR
int i;
//BEGIN
	{long O2M_FOR=c->size - 1;
	for(i=0; i<=O2M_FOR; i+=1) {
		figure::Output(&*(c->fig[i]));
	}};
	Out::Ln();
	Out::Int(c->size, 0);
	Out::String((char*)" figures in container.", 23);
	Out::Ln();
}
//END Output;

/////////////////////////////////////////////
//PROCEDURE FileOutput
void container::FileOutput(FileIO::TFile* outFile, cont* c) {
//VAR
int i;
int flag;
//BEGIN
	{long O2M_FOR=c->size - 1;
	for(i=0; i<=O2M_FOR; i+=1) {
		figure::FileOutput(outFile,&*(c->fig[i]));
	}};
	flag = outFile->Ln();
	flag = outFile->WriteInt(c->size, 0);
	flag = outFile->WriteString((char*)" figures in container.", 23);
	flag = outFile->Ln();
}
//END FileOutput;

/////////////////////////////////////////////
//MODULE INITIALIZATION
void container::O2M_SYS_container() {
	//imports initialisation
	static bool O2M_SYS_was_started(false);
	if (O2M_SYS_was_started) return;
	O2M_SYS_was_started = true;
	In::O2M_SYS_In();
	Out::O2M_SYS_Out();
	FileIO::O2M_SYS_FileIO();
	figure::O2M_SYS_figure();
	figureProc::O2M_SYS_figureProc();
//BEGIN
}
//END container.
