/////////////////////////////////////////////
// This file was generated by O2M compiler //
/////////////////////////////////////////////

#ifndef O2M_H_FILE_figureProc
#define O2M_H_FILE_figureProc
#include "_O2M_sys.h"
#include "c:\prog\O2M\Import\In.h"
#include "c:\prog\O2M\Import\Out.h"
#include "c:\prog\O2M\Import\FileIO.h"
#include "figure.h"
#include "rectangle.h"
#include "triangle.h"
namespace figureProc {
//PROCEDURE Input
figure::Pfig* Input();
//PROCEDURE FileInput
figure::Pfig* FileInput(FileIO::TFile* inFile);
//MODULE INITIALIZATION
void O2M_SYS_figureProc();
}
#endif
